/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_AS_Native_Player_WRAP_H_
#define SWIG_AS_Native_Player_WRAP_H_

class SwigDirector_ASVideoInputEvent : public ASVideoInputEvent, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ASVideoInputEvent(JNIEnv *jenv);
    virtual ~SwigDirector_ASVideoInputEvent();
    virtual void videoOpened(VideoInputParam *para);
    virtual void videoStarted(VideoInputParam *para);
    virtual void videoStopped(VideoInputParam *para);
    virtual void videoClosed(VideoInputParam *para);
    virtual void setVideoInput(ASVideoInput *videoInput);
public:
    bool swig_overrides(int n) {
      return (n < 5 ? swig_override[n] : false);
    }
protected:
    bool swig_override[5];
};

class SwigDirector_ASMediaFileSourceEvent : public ASMediaFileSourceEvent, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ASMediaFileSourceEvent(JNIEnv *jenv);
    virtual ~SwigDirector_ASMediaFileSourceEvent();
    virtual void videoOpened(VideoInputParam *para);
    virtual void videoStarted(VideoInputParam *para);
    virtual void videoStopped(VideoInputParam *para);
    virtual void videoClosed(VideoInputParam *para);
    virtual void setVideoInput(ASVideoInput *videoInput);
public:
    bool swig_overrides(int n) {
      return (n < 5 ? swig_override[n] : false);
    }
protected:
    bool swig_override[5];
};


#endif
