/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_AS_Native_Player_WRAP_H_
#define SWIG_AS_Native_Player_WRAP_H_

class SwigDirector_IVideoDecodeCB : public IVideoDecodeCB, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_IVideoDecodeCB(JNIEnv *jenv);
    virtual ~SwigDirector_IVideoDecodeCB();
    virtual int startVideoDecoding(bool isStart);
    virtual int stopVideoDecoding(bool isStop);
    virtual int recvDecodeData(char *data, int width, int height);
public:
    bool swig_overrides(int n) {
      return (n < 3 ? swig_override[n] : false);
    }
protected:
    bool swig_override[3];
};

class SwigDirector_ASVideoDecodeEvent : public ASVideoDecodeEvent, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ASVideoDecodeEvent(JNIEnv *jenv);
    virtual ~SwigDirector_ASVideoDecodeEvent();
    virtual int startVideoDecoding(bool isStart);
    virtual int stopVideoDecoding(bool isStop);
    virtual int recvDecodeData(char *data, int width, int height);
    virtual int dispayDataOnAndroid(char *data, int width, int height);
public:
    bool swig_overrides(int n) {
      return (n < 4 ? swig_override[n] : false);
    }
protected:
    bool swig_override[4];
};


#endif
