/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_AS_Native_Player_WRAP_H_
#define SWIG_AS_Native_Player_WRAP_H_

class SwigDirector_ASVideoInputEvent : public ASVideoInputEvent, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ASVideoInputEvent(JNIEnv *jenv);
    virtual ~SwigDirector_ASVideoInputEvent();
    virtual void videoOpened(VideoInputParam *para);
    virtual void videoStarted(VideoInputParam *para);
    virtual void videoStopped(VideoInputParam *para);
    virtual void videoClosed(VideoInputParam *para);
public:
    bool swig_overrides(int n) {
      return (n < 4 ? swig_override[n] : false);
    }
protected:
    bool swig_override[4];
};

class SwigDirector_ASVideoInput : public ASVideoInput, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ASVideoInput(JNIEnv *jenv);
    virtual ~SwigDirector_ASVideoInput();
    virtual int videoOpen(char *url, VIDEO_SOURCE srcType);
    virtual int videoStart(VideoInputParam *para);
    virtual int videoStop();
    virtual int videoClose();
public:
    bool swig_overrides(int n) {
      return (n < 4 ? swig_override[n] : false);
    }
protected:
    bool swig_override[4];
};

class SwigDirector_ASNativePlayer : public ASNativePlayer, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ASNativePlayer(JNIEnv *jenv);
    virtual ~SwigDirector_ASNativePlayer();
    virtual void videoOpened(VideoInputParam *para);
    virtual void videoStarted(VideoInputParam *para);
    virtual void videoStopped(VideoInputParam *para);
    virtual void videoClosed(VideoInputParam *para);
public:
    bool swig_overrides(int n) {
      return (n < 4 ? swig_override[n] : false);
    }
protected:
    bool swig_override[4];
};


#endif
