/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.asnetwork.swig;

public class AS_Native_PlayerJNI {
  public final static native long ASNativePlayer_getInstance();
  public final static native void ASNativePlayer_releaseInstance();
  public final static native long new_ASNativePlayer();
  public final static native void delete_ASNativePlayer(long jarg1);
  public final static native int ASNativePlayer_ASOpenFile(long jarg1, ASNativePlayer jarg1_, String jarg2);
  public final static native int ASNativePlayer_ASOpenCodec(long jarg1, ASNativePlayer jarg1_);
  public final static native String ASNativePlayer_getMediaSimpleInfo(long jarg1, ASNativePlayer jarg1_);
  public final static native void ASNativePlayer_isOpenFile_set(long jarg1, ASNativePlayer jarg1_, int jarg2);
  public final static native int ASNativePlayer_isOpenFile_get(long jarg1, ASNativePlayer jarg1_);
}
