/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.asnetwork.swig;

public class ASMediaFileSourceEvent extends ASVideoInputEvent {
  private long swigCPtr;

  protected ASMediaFileSourceEvent(long cPtr, boolean cMemoryOwn) {
    super(AS_Native_PlayerJNI.ASMediaFileSourceEvent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ASMediaFileSourceEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AS_Native_PlayerJNI.delete_ASMediaFileSourceEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    AS_Native_PlayerJNI.ASMediaFileSourceEvent_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    AS_Native_PlayerJNI.ASMediaFileSourceEvent_change_ownership(this, swigCPtr, true);
  }

  public ASMediaFileSourceEvent() {
    this(AS_Native_PlayerJNI.new_ASMediaFileSourceEvent(), true);
    AS_Native_PlayerJNI.ASMediaFileSourceEvent_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void videoOpened(VideoInputParam para) {
    if (getClass() == ASMediaFileSourceEvent.class) AS_Native_PlayerJNI.ASMediaFileSourceEvent_videoOpened(swigCPtr, this, VideoInputParam.getCPtr(para), para); else AS_Native_PlayerJNI.ASMediaFileSourceEvent_videoOpenedSwigExplicitASMediaFileSourceEvent(swigCPtr, this, VideoInputParam.getCPtr(para), para);
  }

  public void videoStarted(VideoInputParam para) {
    if (getClass() == ASMediaFileSourceEvent.class) AS_Native_PlayerJNI.ASMediaFileSourceEvent_videoStarted(swigCPtr, this, VideoInputParam.getCPtr(para), para); else AS_Native_PlayerJNI.ASMediaFileSourceEvent_videoStartedSwigExplicitASMediaFileSourceEvent(swigCPtr, this, VideoInputParam.getCPtr(para), para);
  }

  public void videoStopped(VideoInputParam para) {
    if (getClass() == ASMediaFileSourceEvent.class) AS_Native_PlayerJNI.ASMediaFileSourceEvent_videoStopped(swigCPtr, this, VideoInputParam.getCPtr(para), para); else AS_Native_PlayerJNI.ASMediaFileSourceEvent_videoStoppedSwigExplicitASMediaFileSourceEvent(swigCPtr, this, VideoInputParam.getCPtr(para), para);
  }

  public void videoClosed(VideoInputParam para) {
    if (getClass() == ASMediaFileSourceEvent.class) AS_Native_PlayerJNI.ASMediaFileSourceEvent_videoClosed(swigCPtr, this, VideoInputParam.getCPtr(para), para); else AS_Native_PlayerJNI.ASMediaFileSourceEvent_videoClosedSwigExplicitASMediaFileSourceEvent(swigCPtr, this, VideoInputParam.getCPtr(para), para);
  }

}
