/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.asnetwork.swig;

public class ASMediaNode {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ASMediaNode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ASMediaNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AS_Native_PlayerJNI.delete_ASMediaNode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int packetDataRecv(SWIGTYPE_p_void frame) {
    return AS_Native_PlayerJNI.ASMediaNode_packetDataRecv(swigCPtr, this, SWIGTYPE_p_void.getCPtr(frame));
  }

  public int packetDataSend(SWIGTYPE_p_void frame) {
    return AS_Native_PlayerJNI.ASMediaNode_packetDataSend(swigCPtr, this, SWIGTYPE_p_void.getCPtr(frame));
  }

}
