/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.asnetwork.swig;

public class ASNativePlayer extends ASVideoInputEvent {
  private long swigCPtr;

  protected ASNativePlayer(long cPtr, boolean cMemoryOwn) {
    super(AS_Native_PlayerJNI.ASNativePlayer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ASNativePlayer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AS_Native_PlayerJNI.delete_ASNativePlayer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static ASNativePlayer createNewInstance() {
    long cPtr = AS_Native_PlayerJNI.ASNativePlayer_createNewInstance();
    return (cPtr == 0) ? null : new ASNativePlayer(cPtr, false);
  }

  public static ASNativePlayer getInstance() {
    long cPtr = AS_Native_PlayerJNI.ASNativePlayer_getInstance();
    return (cPtr == 0) ? null : new ASNativePlayer(cPtr, false);
  }

  public static void releaseInstance(ASNativePlayer instance) {
    AS_Native_PlayerJNI.ASNativePlayer_releaseInstance__SWIG_0(ASNativePlayer.getCPtr(instance), instance);
  }

  public static void releaseInstance() {
    AS_Native_PlayerJNI.ASNativePlayer_releaseInstance__SWIG_1();
  }

  public static void setG_instance(ASNativePlayer value) {
    AS_Native_PlayerJNI.ASNativePlayer_g_instance_set(ASNativePlayer.getCPtr(value), value);
  }

  public static ASNativePlayer getG_instance() {
    long cPtr = AS_Native_PlayerJNI.ASNativePlayer_g_instance_get();
    return (cPtr == 0) ? null : new ASNativePlayer(cPtr, false);
  }

  public ASNativePlayer() {
    this(AS_Native_PlayerJNI.new_ASNativePlayer(), true);
  }

  public int playVideo(String filename) {
    return AS_Native_PlayerJNI.ASNativePlayer_playVideo(swigCPtr, this, filename);
  }

  public int stopVideo() {
    return AS_Native_PlayerJNI.ASNativePlayer_stopVideo(swigCPtr, this);
  }

  public void videoOpened(VideoInputParam para) {
    AS_Native_PlayerJNI.ASNativePlayer_videoOpened(swigCPtr, this, VideoInputParam.getCPtr(para), para);
  }

  public void videoStarted(VideoInputParam para) {
    AS_Native_PlayerJNI.ASNativePlayer_videoStarted(swigCPtr, this, VideoInputParam.getCPtr(para), para);
  }

  public void videoStopped(VideoInputParam para) {
    AS_Native_PlayerJNI.ASNativePlayer_videoStopped(swigCPtr, this, VideoInputParam.getCPtr(para), para);
  }

  public void videoClosed(VideoInputParam para) {
    AS_Native_PlayerJNI.ASNativePlayer_videoClosed(swigCPtr, this, VideoInputParam.getCPtr(para), para);
  }

  public void setState(ASPlayState value) {
    AS_Native_PlayerJNI.ASNativePlayer_state_set(swigCPtr, this, value.swigValue());
  }

  public ASPlayState getState() {
    return ASPlayState.swigToEnum(AS_Native_PlayerJNI.ASNativePlayer_state_get(swigCPtr, this));
  }

  public void setFilename(String value) {
    AS_Native_PlayerJNI.ASNativePlayer_filename_set(swigCPtr, this, value);
  }

  public String getFilename() {
    return AS_Native_PlayerJNI.ASNativePlayer_filename_get(swigCPtr, this);
  }

}
