/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.asnetwork.swig;

public class ASNativePlayer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ASNativePlayer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ASNativePlayer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AS_Native_PlayerJNI.delete_ASNativePlayer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static ASNativePlayer createNewInstance() {
    long cPtr = AS_Native_PlayerJNI.ASNativePlayer_createNewInstance__SWIG_0();
    return (cPtr == 0) ? null : new ASNativePlayer(cPtr, false);
  }

  public static ASNativePlayer createNewInstance(String filename) {
    long cPtr = AS_Native_PlayerJNI.ASNativePlayer_createNewInstance__SWIG_1(filename);
    return (cPtr == 0) ? null : new ASNativePlayer(cPtr, false);
  }

  public static void releaseInstance(ASNativePlayer instance) {
    AS_Native_PlayerJNI.ASNativePlayer_releaseInstance(ASNativePlayer.getCPtr(instance), instance);
  }

  public ASNativePlayer(String filename) {
    this(AS_Native_PlayerJNI.new_ASNativePlayer__SWIG_0(filename), true);
  }

  public ASNativePlayer() {
    this(AS_Native_PlayerJNI.new_ASNativePlayer__SWIG_1(), true);
  }

  public int play() {
    return AS_Native_PlayerJNI.ASNativePlayer_play(swigCPtr, this);
  }

  public int stop() {
    return AS_Native_PlayerJNI.ASNativePlayer_stop(swigCPtr, this);
  }

  public int pause() {
    return AS_Native_PlayerJNI.ASNativePlayer_pause(swigCPtr, this);
  }

  public int end() {
    return AS_Native_PlayerJNI.ASNativePlayer_end(swigCPtr, this);
  }

  public void setVideoInputListener(ASVideoInputEvent eventListener) {
    AS_Native_PlayerJNI.ASNativePlayer_setVideoInputListener(swigCPtr, this, ASVideoInputEvent.getCPtr(eventListener), eventListener);
  }

  public void setState(ASPlayState value) {
    AS_Native_PlayerJNI.ASNativePlayer_state_set(swigCPtr, this, value.swigValue());
  }

  public ASPlayState getState() {
    return ASPlayState.swigToEnum(AS_Native_PlayerJNI.ASNativePlayer_state_get(swigCPtr, this));
  }

  public void setFilename(String value) {
    AS_Native_PlayerJNI.ASNativePlayer_filename_set(swigCPtr, this, value);
  }

  public String getFilename() {
    return AS_Native_PlayerJNI.ASNativePlayer_filename_get(swigCPtr, this);
  }

}
