/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.asnetwork.swig;

public class ASNativePlayer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ASNativePlayer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ASNativePlayer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AS_Native_PlayerJNI.delete_ASNativePlayer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static ASNativePlayer getInstance() {
    long cPtr = AS_Native_PlayerJNI.ASNativePlayer_getInstance();
    return (cPtr == 0) ? null : new ASNativePlayer(cPtr, false);
  }

  public static void releaseInstance() {
    AS_Native_PlayerJNI.ASNativePlayer_releaseInstance();
  }

  public ASNativePlayer() {
    this(AS_Native_PlayerJNI.new_ASNativePlayer(), true);
  }

  public int ASOpenFile(String filename) {
    return AS_Native_PlayerJNI.ASNativePlayer_ASOpenFile(swigCPtr, this, filename);
  }

  public int ASOpenCodec() {
    return AS_Native_PlayerJNI.ASNativePlayer_ASOpenCodec(swigCPtr, this);
  }

  public String getMediaSimpleInfo() {
    return AS_Native_PlayerJNI.ASNativePlayer_getMediaSimpleInfo(swigCPtr, this);
  }

  public void setIsOpenFile(int value) {
    AS_Native_PlayerJNI.ASNativePlayer_isOpenFile_set(swigCPtr, this, value);
  }

  public int getIsOpenFile() {
    return AS_Native_PlayerJNI.ASNativePlayer_isOpenFile_get(swigCPtr, this);
  }

}
