/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.asnetwork.swig;

public final class ASPlayState {
  public final static ASPlayState PLAYER_INIT = new ASPlayState("PLAYER_INIT");
  public final static ASPlayState PLAYER_PAUSED = new ASPlayState("PLAYER_PAUSED");
  public final static ASPlayState PLAYER_START = new ASPlayState("PLAYER_START");
  public final static ASPlayState PLAYER_STOP = new ASPlayState("PLAYER_STOP");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ASPlayState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ASPlayState.class + " with value " + swigValue);
  }

  private ASPlayState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ASPlayState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ASPlayState(String swigName, ASPlayState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ASPlayState[] swigValues = { PLAYER_INIT, PLAYER_PAUSED, PLAYER_START, PLAYER_STOP };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

