/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.asnetwork.swig;

public class ASVideoInputEvent {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ASVideoInputEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ASVideoInputEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AS_Native_PlayerJNI.delete_ASVideoInputEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    AS_Native_PlayerJNI.ASVideoInputEvent_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    AS_Native_PlayerJNI.ASVideoInputEvent_change_ownership(this, swigCPtr, true);
  }

  public ASVideoInputEvent() {
    this(AS_Native_PlayerJNI.new_ASVideoInputEvent(), true);
    AS_Native_PlayerJNI.ASVideoInputEvent_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void videoOpened(VideoInputParam para) {
    AS_Native_PlayerJNI.ASVideoInputEvent_videoOpened(swigCPtr, this, VideoInputParam.getCPtr(para), para);
  }

  public void videoStarted(VideoInputParam para) {
    AS_Native_PlayerJNI.ASVideoInputEvent_videoStarted(swigCPtr, this, VideoInputParam.getCPtr(para), para);
  }

  public void videoStopped(VideoInputParam para) {
    AS_Native_PlayerJNI.ASVideoInputEvent_videoStopped(swigCPtr, this, VideoInputParam.getCPtr(para), para);
  }

  public void videoClosed(VideoInputParam para) {
    AS_Native_PlayerJNI.ASVideoInputEvent_videoClosed(swigCPtr, this, VideoInputParam.getCPtr(para), para);
  }

}
