/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.asnetwork.swig;

public class ASVideoDecodeEvent extends IVideoDecodeCB {
  private long swigCPtr;

  protected ASVideoDecodeEvent(long cPtr, boolean cMemoryOwn) {
    super(AS_Native_PlayerJNI.ASVideoDecodeEvent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ASVideoDecodeEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AS_Native_PlayerJNI.delete_ASVideoDecodeEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    AS_Native_PlayerJNI.ASVideoDecodeEvent_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    AS_Native_PlayerJNI.ASVideoDecodeEvent_change_ownership(this, swigCPtr, true);
  }

  public ASVideoDecodeEvent() {
    this(AS_Native_PlayerJNI.new_ASVideoDecodeEvent(), true);
    AS_Native_PlayerJNI.ASVideoDecodeEvent_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public int startVideoDecoding(boolean isStart) {
    return (getClass() == ASVideoDecodeEvent.class) ? AS_Native_PlayerJNI.ASVideoDecodeEvent_startVideoDecoding(swigCPtr, this, isStart) : AS_Native_PlayerJNI.ASVideoDecodeEvent_startVideoDecodingSwigExplicitASVideoDecodeEvent(swigCPtr, this, isStart);
  }

  public int stopVideoDecoding(boolean isStop) {
    return (getClass() == ASVideoDecodeEvent.class) ? AS_Native_PlayerJNI.ASVideoDecodeEvent_stopVideoDecoding(swigCPtr, this, isStop) : AS_Native_PlayerJNI.ASVideoDecodeEvent_stopVideoDecodingSwigExplicitASVideoDecodeEvent(swigCPtr, this, isStop);
  }

  public void setIsStart(boolean value) {
    AS_Native_PlayerJNI.ASVideoDecodeEvent_isStart_set(swigCPtr, this, value);
  }

  public boolean getIsStart() {
    return AS_Native_PlayerJNI.ASVideoDecodeEvent_isStart_get(swigCPtr, this);
  }

  public void setIsStop(boolean value) {
    AS_Native_PlayerJNI.ASVideoDecodeEvent_isStop_set(swigCPtr, this, value);
  }

  public boolean getIsStop() {
    return AS_Native_PlayerJNI.ASVideoDecodeEvent_isStop_get(swigCPtr, this);
  }

}
