/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.asnetwork.swig;

public class ucArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ucArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ucArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AS_Native_PlayerJNI.delete_ucArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ucArray(int nelements) {
    this(AS_Native_PlayerJNI.new_ucArray(nelements), true);
  }

  public short getitem(int index) {
    return AS_Native_PlayerJNI.ucArray_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, short value) {
    AS_Native_PlayerJNI.ucArray_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_unsigned_char cast() {
    long cPtr = AS_Native_PlayerJNI.ucArray_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static ucArray frompointer(SWIGTYPE_p_unsigned_char t) {
    long cPtr = AS_Native_PlayerJNI.ucArray_frompointer(SWIGTYPE_p_unsigned_char.getCPtr(t));
    return (cPtr == 0) ? null : new ucArray(cPtr, false);
  }

}
