/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.asnetwork.swig;

public final class VideoInputState {
  public final static VideoInputState AS_INIT = new VideoInputState("AS_INIT");
  public final static VideoInputState AS_Started = new VideoInputState("AS_Started");
  public final static VideoInputState AS_Stopped = new VideoInputState("AS_Stopped");
  public final static VideoInputState AS_Opened = new VideoInputState("AS_Opened");
  public final static VideoInputState AS_Closed = new VideoInputState("AS_Closed");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static VideoInputState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + VideoInputState.class + " with value " + swigValue);
  }

  private VideoInputState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private VideoInputState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private VideoInputState(String swigName, VideoInputState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static VideoInputState[] swigValues = { AS_INIT, AS_Started, AS_Stopped, AS_Opened, AS_Closed };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

