/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.asnetwork.swig;

public class VideoInputParam {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VideoInputParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VideoInputParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AS_Native_PlayerJNI.delete_VideoInputParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSrc_width(int value) {
    AS_Native_PlayerJNI.VideoInputParam_src_width_set(swigCPtr, this, value);
  }

  public int getSrc_width() {
    return AS_Native_PlayerJNI.VideoInputParam_src_width_get(swigCPtr, this);
  }

  public void setSrc_height(int value) {
    AS_Native_PlayerJNI.VideoInputParam_src_height_set(swigCPtr, this, value);
  }

  public int getSrc_height() {
    return AS_Native_PlayerJNI.VideoInputParam_src_height_get(swigCPtr, this);
  }

  public void setDest_width(int value) {
    AS_Native_PlayerJNI.VideoInputParam_dest_width_set(swigCPtr, this, value);
  }

  public int getDest_width() {
    return AS_Native_PlayerJNI.VideoInputParam_dest_width_get(swigCPtr, this);
  }

  public void setDest_height(int value) {
    AS_Native_PlayerJNI.VideoInputParam_dest_height_set(swigCPtr, this, value);
  }

  public int getDest_height() {
    return AS_Native_PlayerJNI.VideoInputParam_dest_height_get(swigCPtr, this);
  }

  public void setColorSpaceType(int value) {
    AS_Native_PlayerJNI.VideoInputParam_colorSpaceType_set(swigCPtr, this, value);
  }

  public int getColorSpaceType() {
    return AS_Native_PlayerJNI.VideoInputParam_colorSpaceType_get(swigCPtr, this);
  }

  public void setCurrentState(int value) {
    AS_Native_PlayerJNI.VideoInputParam_currentState_set(swigCPtr, this, value);
  }

  public int getCurrentState() {
    return AS_Native_PlayerJNI.VideoInputParam_currentState_get(swigCPtr, this);
  }

  public void setCurrentActionState(int value) {
    AS_Native_PlayerJNI.VideoInputParam_currentActionState_set(swigCPtr, this, value);
  }

  public int getCurrentActionState() {
    return AS_Native_PlayerJNI.VideoInputParam_currentActionState_get(swigCPtr, this);
  }

  public void setNextAction(int value) {
    AS_Native_PlayerJNI.VideoInputParam_nextAction_set(swigCPtr, this, value);
  }

  public int getNextAction() {
    return AS_Native_PlayerJNI.VideoInputParam_nextAction_get(swigCPtr, this);
  }

  public void setDecodeProcess(SWIGTYPE_p_ASVideoDecodeProcess value) {
    AS_Native_PlayerJNI.VideoInputParam_decodeProcess_set(swigCPtr, this, SWIGTYPE_p_ASVideoDecodeProcess.getCPtr(value));
  }

  public SWIGTYPE_p_ASVideoDecodeProcess getDecodeProcess() {
    long cPtr = AS_Native_PlayerJNI.VideoInputParam_decodeProcess_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ASVideoDecodeProcess(cPtr, false);
  }

  public void setFileSource(SWIGTYPE_p_ASMediaFileSource value) {
    AS_Native_PlayerJNI.VideoInputParam_fileSource_set(swigCPtr, this, SWIGTYPE_p_ASMediaFileSource.getCPtr(value));
  }

  public SWIGTYPE_p_ASMediaFileSource getFileSource() {
    long cPtr = AS_Native_PlayerJNI.VideoInputParam_fileSource_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ASMediaFileSource(cPtr, false);
  }

  public void setVideoState(SWIGTYPE_p_pVideoState value) {
    AS_Native_PlayerJNI.VideoInputParam_videoState_set(swigCPtr, this, SWIGTYPE_p_pVideoState.getCPtr(value));
  }

  public SWIGTYPE_p_pVideoState getVideoState() {
    return new SWIGTYPE_p_pVideoState(AS_Native_PlayerJNI.VideoInputParam_videoState_get(swigCPtr, this), true);
  }

  public VideoInputParam() {
    this(AS_Native_PlayerJNI.new_VideoInputParam(), true);
  }

}
